export const USER_SIGN_IN_REQUEST = "USER_SIGN_IN_REQUEST"
export const USER_SIGN_IN_SUCCESS = "USER_SIGNIN_SUCCESS"
export const USER_SIGN_IN_FAIL = "USER_SIGNIN_FAIL"

export const USER_SIGN_OUT_REQUEST = "USER_SIGN_OUT_REQUEST"
export const USER_SIGN_OUT_SUCCESS = "USER_SIGN_OUT_SUCCESS"
export const USER_SIGN_OUT_FAIL = "USER_SIGN_OUT_FAIL"

export const USER_REGISTER_REQUEST = "USER_REGISTER_REQUEST"
export const USER_REGISTER_SUCCESS = "USER_REGISTER_SUCCESS"
export const USER_REGISTER_FAIL = "USER_REGISTER_FAIL"